### ISSUE TITLE
theme search not working and frontend error

### ISSUE THREAD

**Issue by MertcanGokgoz** [godofredoninja/simply#18]
Hello

Im using ghost 1.21.1 version and I see the following error, I think have been changes in the API

note: API access is enable

```
https://mertcangokgoz.com/posts/?limit=all&include=tags&formats=plaintext&client_id=ghost-frontend&client_secret=secret HTTP 404
````

Ghost log

```
{
   "name":"Log",
   "hostname":
   "pid":2138,
   "level":50,
   "err":{
      "id":"81099b50-1062-11e8-a3b4-4188c16b592a",
      "domain":"https://mertcangokgoz.com",
      "code":null,
      "name":"ValidationError",
      "statusCode":422,
      "level":"normal",
      "message":"The request failed validation.",
      "context":"Error parsing filter",
      "help":"For more information on how to use filter, see http://api.ghost.org/docs/filter",
      "stack":"ValidationError: The request failed validation.\n    at new ValidationError (/var/www/ghost/versions/1.21.1/node_modules/ghost-ignition/lib/errors/index.js:115:23)\n    at Object.combineFilters (/var/www/ghost/versions/1.21.1/core/server/models/plugins/filter.js:27:19)\n    at fetchAndCombineFilters (/var/www/ghost/versions/1.21.1/core/server/models/plugins/filter.js:147:41)\n    at applyDefaultAndCustomFilters (/var/www/ghost/versions/1.21.1/core/server/models/plugins/filter.js:169:22)\n    at Function.findPage (/var/www/ghost/versions/1.21.1/core/server/models/base/index.js:559:24)\n    at modelQuery (/var/www/ghost/versions/1.21.1/core/server/api/posts.js:56:32)\n    at runTask (/var/www/ghost/versions/1.21.1/core/server/lib/promise/pipeline.js:16:24)\n    at /var/www/ghost/versions/1.21.1/core/server/lib/promise/pipeline.js:26:20\n    at tryCatcher (/var/www/ghost/versions/1.21.1/node_modules/bluebird/js/release/util.js:16:23)\n    at Object.gotValue (/var/www/ghost/versions/1.21.1/node_modules/bluebird/js/release/reduce.js:157:18)\n    at Object.gotAccum (/var/www/ghost/versions/1.21.1/node_modules/bluebird/js/release/reduce.js:144:25)\n    at Object.tryCatcher (/var/www/ghost/versions/1.21.1/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/ghost/versions/1.21.1/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/var/www/ghost/versions/1.21.1/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/var/www/ghost/versions/1.21.1/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/var/www/ghost/versions/1.21.1/node_modules/bluebird/js/release/promise.js:693:18)\n    at Async._drainQueue (/var/www/ghost/versions/1.21.1/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/var/www/ghost/versions/1.21.1/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/var/www/ghost/versions/1.21.1/node_modules/bluebird/js/release/async.js:17:14)\n\nError: Query Error: unexpected character in filter at char 6\ntags:[]+id:-59b583dc71d889\n------^\nExpecting 'NULL', 'TRUE', 'FALSE', 'NUMBER', 'LITERAL', 'STRING', got 'RBRACKET'\n    at Object.parser.parseError (/var/www/ghost/versions/1.21.1/node_modules/ghost-gql/dist/parser.js:320:12)\n    at Object.parse (/var/www/ghost/versions/1.21.1/node_modules/ghost-gql/dist/parser.js:236:22)\n    at Object.exports.parse (/var/www/ghost/versions/1.21.1/node_modules/ghost-gql/lib/gql.js:19:19)\n    at /var/www/ghost/versions/1.21.1/core/server/models/plugins/filter.js:24:46\n    at arrayMap (/var/www/ghost/versions/1.21.1/node_modules/lodash/lodash.js:660:23)\n    at Function.map (/var/www/ghost/versions/1.21.1/node_modules/lodash/lodash.js:9571:14)\n    at Object.combineFilters (/var/www/ghost/versions/1.21.1/core/server/models/plugins/filter.js:23:24)\n    at fetchAndCombineFilters (/var/www/ghost/versions/1.21.1/core/server/models/plugins/filter.js:147:41)\n    at applyDefaultAndCustomFilters (/var/www/ghost/versions/1.21.1/core/server/models/plugins/filter.js:169:22)\n    at Function.findPage (/var/www/ghost/versions/1.21.1/core/server/models/base/index.js:559:24)\n    at modelQuery (/var/www/ghost/versions/1.21.1/core/server/api/posts.js:56:32)\n    at runTask (/var/www/ghost/versions/1.21.1/core/server/lib/promise/pipeline.js:16:24)\n    at /var/www/ghost/versions/1.21.1/core/server/lib/promise/pipeline.js:26:20\n    at tryCatcher (/var/www/ghost/versions/1.21.1/node_modules/bluebird/js/release/util.js:16:23)\n    at Object.gotValue (/var/www/ghost/versions/1.21.1/node_modules/bluebird/js/release/reduce.js:157:18)\n    at Object.gotAccum (/var/www/ghost/versions/1.21.1/node_modules/bluebird/js/release/reduce.js:144:25)"
   },
   "msg":"The request failed validation.",
   "time":"2018-02-13T02:06:29.269Z",
   "v":0
}
```

**Comment by MertcanGokgoz** [comment]
@godofredoninja Can you help?

**Comment by godofredoninja** [comment]
Hi @MertcanGokgoz 

I think the problem is with the ghost. update your ghost to the latest version

https://github.com/TryGhost/Ghost/releases

**Comment by MertcanGokgoz** [comment]
I am using version 1.21.2, it still does not work and gives an error.

**Comment by MertcanGokgoz** [comment]
Hello @godofredoninja 

I'm still having this problem, search functions are not working(never worked). The ghost team is not helping with the issue.

the problem still continues. 👎
